["broot/skins/catppuccin"]
type = "archive"
# Pin to a specific commit for reproducible updates.
url = "https://github.com/catppuccin/broot/archive/404357d2e5abbf8d28658796696995d4410e3390.tar.gz"
exact = true
stripComponents = 2
include = ["*/themes/**"]
refreshPeriod = "168h"

["git/themes/catppuccin-delta.gitconfig"]
type = "file"
# Pin to a specific commit for reproducible updates.
url = "https://raw.githubusercontent.com/catppuccin/delta/74b47a345638a2f19b3e5bdb9d7e4984066f9ac7/catppuccin.gitconfig"
refreshPeriod = "168h"

["zsh/themes/catppuccin-fzf-macchiato.sh"]
type = "file"
# Pin to a specific commit for reproducible updates.
url = "https://raw.githubusercontent.com/catppuccin/fzf/7c2e05606f2e75840b1ba367b1f997cd919809b3/themes/catppuccin-fzf-macchiato.sh"
refreshPeriod = "168h"

["fsh/catppuccin-macchiato.ini"]
type = "file"
# Pin to a specific commit for reproducible updates.
url = "https://raw.githubusercontent.com/catppuccin/zsh-fsh/a9bdf479f8982c4b83b5c5005c8231c6b3352e2a/themes/catppuccin-macchiato.ini"
refreshPeriod = "168h"
