alias ls='ls -G'
alias ll='ls -l'
alias la='ls -A'
alias lr='ls -R'
alias lla='ls -lA'
alias llh='ls -lh'
alias llr='ls -lR'
alias llar='ls -lAR'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias vimr='vimr --cur-env'
alias vim='nvim'
alias view='nvim -R'
alias mvim='vimr'
