# Configuration for markdownlint-cli2
# Used by Neovim (conform.nvim / nvim-lint) and agents

# Rule overrides
config:
  # Disable line-length — one sentence per line convention produces long lines
  MD013: false
  # Allow inline HTML — agent Markdown files use <example>, <system-reminder>, etc.
  MD033: false
  # Don't require first line to be a top-level heading — files may start with frontmatter or comments
  MD041: false
